// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKjfEfrJoJ_uLKmcOfft3Bimbj6pECxo',
    appId: '1:514380928389:web:570f7f395637e76cc560ec',
    messagingSenderId: '514380928389',
    projectId: 'flashcards-b67fb',
    authDomain: 'flashcards-b67fb.firebaseapp.com',
    storageBucket: 'flashcards-b67fb.appspot.com',
    measurementId: 'G-QZ8DJC1RRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcv-NnkGFmF9MqjudglpLdBPMdBHYcp_w',
    appId: '1:514380928389:android:9b113c36e536952cc560ec',
    messagingSenderId: '514380928389',
    projectId: 'flashcards-b67fb',
    storageBucket: 'flashcards-b67fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpC_6cxJB1is1EPe4IsBUw_uUx96T9vUc',
    appId: '1:514380928389:ios:c8632509e6856c46c560ec',
    messagingSenderId: '514380928389',
    projectId: 'flashcards-b67fb',
    storageBucket: 'flashcards-b67fb.appspot.com',
    iosClientId: '514380928389-77cgg1afhlv8ka69d5kc8125pisprdsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashCards',
  );
}
